### ISSUE TITLE
Python 3.6 support should be dropped

### ISSUE THREAD

**Issue by maartenbreddels** [conda-forge/filesystem-spec-feedstock#63]
Hi,

I see in CI:
 * https://github.com/vaexio/vaex/runs/5359548415?check_suite_focus=true
```
../../../micromamba/envs/vaex-dev/lib/python3.6/site-packages/s3fs/__init__.py:1: in <module>
    from .core import S3FileSystem, S3File
../../../micromamba/envs/vaex-dev/lib/python3.6/site-packages/s3fs/core.py:25: in <module>
    from s3fs.utils import S3BucketRegionCache, ParamKwargsHelper, _get_brange, FileExpired
../../../micromamba/envs/vaex-dev/lib/python3.6/site-packages/s3fs/utils.py:3: in <module>
    from contextlib import contextmanager, AsyncExitStack
E   ImportError: cannot import name 'AsyncExitStack'
```

I think Python 3.6 was delisted in setup.py in https://github.com/fsspec/s3fs/pull/582/commits/a0e31dc81a5d9a0055dd1d5500d7a6adafd30a3d but not in the recipe

not sure which version started this.

**Comment by martindurant** [comment]
You are quite right, py36 should not have been built. I suppose we need a patch?

**Comment by maartenbreddels** [comment]
See also https://github.com/jupyter/nbclient/issues/194 to mark a package as broken

**Comment by candalfigomoro** [comment]
I confirm that the conda package (the original build) for version 2023.3.0 is broken with Python 3.7 because this change made Python >=3.8 mandatory: https://github.com/fsspec/filesystem_spec/commit/bec9a8d6e5962da4cc2473c8c7924f002033fad3

If you run version 2023.3.0 with Python 3.7 you get this error:
`ModuleNotFoundError: No module named 'importlib.metadata'`

Version 2023.1.0 is the last version compatible with Python <3.8
